AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    Runtime: python3.11

Resources:
  ############################# DynamoDB Table##########
  VpcResourcesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: VpcResources
      AttributeDefinitions:
        - AttributeName: ResourceId
          AttributeType: S
      KeySchema:
        - AttributeName: ResourceId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # #################Cognito User Pool###################
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: VPCAPIUserPool

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: VPCAPIClient
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false

  ###############API Gateway###########################
  VpcApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: VpcApiGateway
      StageName: dev
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt CognitoUserPool.Arn
            Identity:
              Header: Authorization
              ValidationExpression: .* 
      EndpointConfiguration: REGIONAL
      Cors:
        AllowHeaders: "'Content-Type,Authorization'"
        AllowMethods: "'OPTIONS,GET,POST'"
        AllowOrigin: "'*'"

  ###################### Lambda Function to Create VPC###################
  CreateVpcFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.create_vpc
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonEC2FullAccess
      Environment:
        Variables:
          TABLE_NAME: VpcResources
      Events:
        CreateVpcAPI:
          Type: Api
          Properties:
            RestApiId: !Ref VpcApiGateway  
            Path: /vpc/create
            Method: POST

  # #####################Lambda Function to Get Resources#######################
  GetVpcFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.get_resources
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          TABLE_NAME: VpcResources
      Events:
        GetVpcAPI:
          Type: Api
          Properties:
            RestApiId: !Ref VpcApiGateway  # Attach to API Gateway
            Path: /vpc/resources
            Method: GET